CREATE TABLE BANK_ACCOUNTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    BALANCE NUMBER(12,2)
);

INSERT INTO BANK_ACCOUNTS VALUES (1, 'Bank A', 50000);
INSERT INTO BANK_ACCOUNTS VALUES (2, 'Bank B', 30000);
INSERT INTO BANK_ACCOUNTS VALUES (3, 'Bank C', 30000);
INSERT INTO BANK_ACCOUNTS VALUES (4, 'Bank D', 60000);

COMMIT;

SELECT * FROM BANK_ACCOUNTS;
CREATE OR REPLACE PROPERTY GRAPH BANK_GRAPH

VERTEX TABLES (
    BANK_ACCOUNTS
        KEY (ID)
        LABEL ACCOUNTS
        PROPERTIES (ID, NAME, BALANCE)
)

EDGE TABLES (
    BANK_TRANSFERS
        SOURCE KEY (FROM_ACCOUNT)
        REFERENCES BANK_ACCOUNTS (ID)

        DESTINATION KEY (TO_ACCOUNT)
        REFERENCES BANK_ACCOUNTS (ID)

        LABEL TRANSFERS
        PROPERTIES (TRANSFER_ID, AMOUNT)
);