CREATE TABLE STUDENT (
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR2(100),
AGE INT,
);
CREATE TABLE PRODUCT(
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100),
    PRODUCT_PRICE NUMBER(10,2)
);
INSERT ALL
 INTO PRODUCT VALUES(1 , 'LAPTOP' , 1200)
 INTO PRODUCT VALUES(2 , 'SMARTPHONE' , 3000)
SELECT 1 FROM DUAL;
COMMIT;
SELECT * FROM PRODUCT;
